// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbschema

import (
	"database/sql"
)

type User struct {
	ID             int32          `json:"id"`
	Email          string         `json:"email"`
	Name           string         `json:"name"`
	HashedPassword string         `json:"hashed_password"`
	ProfilePicUrl  sql.NullString `json:"profile_pic_url"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}
